# Vim-like to alias to exit
alias q='exit'

# Change to previous directory
alias bd='cd $OLDPWD'

# Navigating through parent directory
alias ..="cd .."
alias ..2="cd ../../"
alias ..3="cd ../../../"
alias ..4="cd ../../../../"
alias ..5="cd ../../../../../"

# Clear terminal (finger-saver, instead of <c-l>)
alias c="clear"

# Safer file removals
# could change to mv $1 ~/.trash to make this even safer
alias rm='rm -I'

# Safer file movements, without overwriting
alias mv='mv -n'

# Untar files (I can't never remember those flags)
alias untar='tar -zxvf'

# evince pdf viewer
alias ev='evince'

# ls
alias sl='ls'
alias l='ls'
alias la='ls -A'
alias ll='ls -AlFh'
alias lla='ls -AlFh'

if [ -x "$(command -v ag)" ]; then
    # use ag, not ack
    # https://github.com/ggreer/the_silver_searcher
    alias ack='ag'
    alias a='ag'
else
    # but ack-grep is easier to install w/o sudo access,
    # alias below ignores gitignore'd files (like ag does by default)
    # to use ack outside of git repos, type out ack
    alias a="git ls-files --others --cached --exclude-standard | ack -x"
fi

if [ -x "$(command -v nvim)" ]; then
    # use neovim, not vim, not vi
    # https://github.com/neovim/neovim
    # to really use vim, type vim in full
    alias v='nvim'
    alias nv='nvim'
elif [ -x "$(command -v vim)" ]; then
    alias v='vim'
else
    alias v='vi'
fi

# copy / paste to clipboard
alias clipcopy="xclip -sel clip"
alias clippaste="xclip -sel clip -o"

# maybe try again https://gist.github.com/JuggoPop/10706934
alias gg="git s"

# most of the time, I want rsync to do this
alias _rsync="rsync -ahR --info=progress2"

# history+grep
alias _histgrep="history | grep"

# in places where I do not want ssh-agent running all the time
alias _ssh-add="eval \"$(ssh-agent -s)\" && ssh-add"

# quick pw generator
alias _genpw="openssl rand -base64 16"
